---
title: "R Notebook"
output: html_notebook
---

```{r}
# Import dependencies
library(dplyr)
```


```{r}
## Deliverable 1
# Import and read in the MechaCar_mpg.csv file as a dataframe
mpg_df <- read.csv("Resources/MechaCar_mpg.csv")
```


```{r}
# Perform linear regression on all six variables with the df as the data parameter
lm(mpg ~ vehicle_length + vehicle_weight + spoiler_angle + ground_clearance + AWD, data=mpg_df)
```
```{r}
# Use the Summary function to determine the p-value and the r-squared value for the linear regression model
summary(lm(mpg ~ vehicle_length + vehicle_weight + spoiler_angle + ground_clearance + AWD, data=mpg_df))
```
```{r}
## Delieverable 2
# Import and read in the Suspension_Coil.csv file as a dataframe
coil_df <- read.csv("Resources/Suspension_Coil.csv")
```

```{r}
# Create a total_sumarry dataframe that includes mean, median, variance, standard deviation of suspension coil's PSI
total_summary <- coil_df %>% summarize(Mean=mean(PSI), Median=median(PSI), Variance=var(PSI), SD=sd(PSI))

total_summary

```


```{r}
# Create a lot_summary df that groups each manufacturing lot by the mean, median, var, and sd of the PSI
lot_summary <-
  coil_df %>% 
    group_by(Manufacturing_Lot) %>%
      summarize(Mean=mean(PSI), Median=median(PSI), Variance=var(PSI), SD=sd(PSI))

lot_summary
```


```{r}
## Deliverable 3
# Use t.test() to determine if the PSI across all manufacturing lots is statistically different from the pop mean of 1500 lbs per sq inch
t.test(coil_df$PSI, mu=1500)
```

```{r}
# Use t.test() to determine if the PSI for each manufacturing lot is statistically different from the pop mean of 1500 lbs per sq inch

# Lot 1
lot_1 = subset(coil_df, Manufacturing_Lot == "Lot1")
t.test(data=lot_1, x=lot_1$PSI, mu=1500)
```


```{r}
# Lot 2
lot_2 = subset(coil_df, Manufacturing_Lot == "Lot2")
t.test(data=lot_2, x=lot_2$PSI, mu=1500)
```

```{r}
# Lot 3
lot_3 = subset(coil_df, Manufacturing_Lot == "Lot3")
t.test(data=lot_3, x=lot_3$PSI, mu=1500)
```

